services:
  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:  # depends_onでヘルスチェックに対応
        condition: service_healthy
    networks:
      - go-sns-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
    networks:
      - go-sns-network

networks:
  go-sns-network: