services:
  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:  # depends_onでヘルスチェックに対応
        condition: service_healthy
    networks:
      - go-sns-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "sqlite3", "/app/database/database.sql", "SELECT 1;"]
      interval: 100s
      timeout: 100s
      retries: 3
      start_period: 3s
    networks:
      - go-sns-network

  db:
    image: nouchka/sqlite3
    volumes:
      - ./backend/database/database.sql:/app/database/database.sql

networks:
  go-sns-network: